### ISSUE TITLE
ERB snippets in .js.erb?

### ISSUE THREAD

**Issue by AlexVPopov** [matthewrobertson/ERB-Sublime-Snippets#13]
Is there a way to get this package working in **.js.erb** and not only in **.html.erb**?

**Comment by ckib16** [comment]
Just to clarify the above comments... Do you have to change the scope inside each individual snippet file that we want o work with .js.erb? Or is there some global way to expand the scope of all snippets in this package to include .js.erb?

Thanks very much, fantastic Sublime Package.

**Comment by guilhermesimoes** [comment]
Yes, you have to change the scope inside each individual snippet file.

But you can easily do that using find-and-replace.

**Comment by ckib16** [comment]
Great, thanks very much. That's a good tip. Much appreciated, @guilhermesimoes !
