### ISSUE TITLE
Clarify README.md

### ISSUE THREAD

**Issue by jasonharrison** [matthewrobertson/ERB-Sublime-Snippets#22]
We may consider clarifying the tab triggers listed in [README.md](https://github.com/matthewrobertson/ERB-Sublime-Snippets/blob/master/README.md) by noting that the underscores indicate empty space surrounding the trigger.

**Comment by earliest** [comment]
Agree, I am a new user and spent quite some time to figure it out until I saw this comment.

**Comment by matthewrobertson** [comment]
The readme is supposed to be markdown. It seems like something changed in github that broke the rendering. I will look into it.
